# Generated by Django 3.2.16 on 2022-10-11 08:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
                ('battery_percentage', models.CharField(max_length=16)),
                ('mobile_make_model', models.CharField(max_length=256)),
                ('os_version', models.CharField(max_length=256)),
                ('mac_id', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
