# Generated by Django 3.2.16 on 2022-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
